### ISSUE TITLE
Unable to initialize editor

### ISSUE THREAD

**Issue by yonaichin** [imgly/pesdk-react-demo#1]
Using node ```8.6.0``` & photoeditorsdk ```4.1.2```

run
```
npm install
npm start
```
then visit ```localhost:8081/build/index.html``` will encounter this error

```
VM170:1 Uncaught SyntaxError: Unexpected token Y in JSON at position 0
    at JSON.parse (<anonymous>)
    at e._parseLicense (application.js:12988)
    at new e (application.js:12988)
    at new t (application.js:12969)
    at t._initSDK (application.js:12896)
    at new t (application.js:12896)
    at new t (application.js:12912)
    at application.js:16402
    at measureLifeCyclePerf (application.js:16183)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (application.js:16401)
```

Screenshot: 
![alt text](https://imgur.com/Oy8YvlX.png "Logo Title Text 1")

**Comment by lukaszkomar93** [comment]
Quite similar case, using node `8.3.0` and photoeditorsdk `4.1.2`, was able to run the app, but after trying to upload a photo I get the following result

screenshot:
![image](https://user-images.githubusercontent.com/8258799/34821283-7a30354a-f6c3-11e7-884e-1787f068cc14.png)

**Comment by yonaichin** [comment]
@lukaszkomar93 Can you show me your ```application.js``` file?

Still have the same issue when import license as string.

Thanks in advance.

**Comment by lukaszkomar93** [comment]
@yonaichin There are my credentials in the license place, so I can't paste 'em of course, but you shall be fine with yours. Keep in mind that you have to single-quote the license place, because there are double-quotes in the license itself.

```js
import React from 'react'
import ReactDOM from 'react-dom'

// import PhotoEditorDesktopUI from 'photoeditorsdk/js/PhotoEditorSDK.UI.DesktopUI.js'
import PhotoEditorReactUI from 'photoeditorsdk/js/PhotoEditorSDK.UI.ReactUI.js'

class ApplicationComponent extends React.Component {
  render () {
    // const { ReactComponent } = PhotoEditorDesktopUI;
    const { ReactComponent } = PhotoEditorReactUI;
    return (<ReactComponent
      license='{"owner":"ownerName"...N2f4YqUcKI/sCQ="}'
      assets={{
        baseUrl: '/node_modules/photoeditorsdk/assets'
      }}
      style={{
        width: 1024,
        height: 576
      }} />)
  }
}

window.onload = function () {
  const container = document.querySelector('.js-app')
  ReactDOM.render(<ApplicationComponent />, container)
}

```

**Comment by yonaichin** [comment]
@lukaszkomar93 
Thanks for the help.
I see where the problem is.

```apiKey``` in configuration was a single string at pesdk version ```3.6```.

In pesdk version ```4```, the license is a JSON string, which contains a lot more informations

**Comment by lukaszkomar93** [comment]
Glad I could be of help, good luck with further development :muscle:
