### ISSUE TITLE
Event listener for Export

### ISSUE THREAD

**Issue by AkashHC13** [imgly/pesdk-react-demo#7]
In Editor - Export function override is not exposed. [Docs](https://docs.photoeditorsdk.com/apidocs/html5/v4/PhotoEditorSDK.UI.DesktopUI.html)
I wanna override the export functionality with my own function, which basically uploads the image to an s3 bucket.

**Comment by AndyNeale** [comment]
See NadimD's excellent answer to another issue here:

https://github.com/imgly/pesdk-react-demo/issues/5#issuecomment-412988002

**Comment by keiwando** [comment]
You have to use the `ui` property of the [ReactComponent](https://docs.photoeditorsdk.com/apidocs/html5/v4/PhotoEditorSDK.UI.DesktopUI.ReactComponent.html).

Examples for this and more details have now also been added to the README.
