### ISSUE TITLE
An Error has occurred while rendering the image

### ISSUE THREAD

**Issue by MatteoGioioso** [imgly/pesdk-react-demo#8]
It happens with every image that is not loaded locally

Ex: 

Working correctly
```
window.onload = function () {
  const container = document.querySelector('.js-app')
  const image = new Image()
  image.src = '/example.png' //Image loaded locally
  ReactDOM.render(<ApplicationComponent image={image} />, container)
}
```

Not working
```
window.onload = function () {
  const container = document.querySelector('.js-app')
  const image = new Image()
  image.src = 'https://images.unsplash.com/photo-1542838077-5fd2ba553bbe'
  ReactDOM.render(<ApplicationComponent image={image} />, container)
}
```

` An error occurred while rendering: Failed to execute 'texImage2D' on 'WebGLRenderingContext': Tainted canvases may not be loaded.  `

**Comment by AndyNeale** [comment]
After setting `image.src`, also set `image.crossOrigin = 'anonymous'` - and that assumes the server you're downloading images from is sending the correct CORS headers. If not... erm, I'm not sure what you'd do, to be honest...

**Comment by keiwando** [comment]
@AndyNeale That is correct. For anyone else running into the same problems, we have an FAQ page on CORS:

https://docs.photoeditorsdk.com/guides/html5/v4/introduction/faq/cors

**Comment by mppbell** [comment]
@AndyNeale That link is no longer active unfortunately. Is there any follow up or update to this problem.
